---
openstack_host_distro_packages:
  - apparmor-utils
  - apt-transport-https
  - bridge-utils
  - cgroup-lite
  - curl
  - dmeventd
  - dstat
  - ebtables
  - htop
  - iptables
  - irqbalance
  - libkmod2
  - lvm2
  - python-software-properties
  - rsync
  - rsyslog
  - sysstat
  - time
  - vlan
  - wget
lxc_hosts_distro_packages:
  - apparmor
  - apparmor-profiles
  - apparmor-utils
  - aria2
  - bridge-utils
  - btrfs-tools
  - cgmanager
  - cgroup-lite
  - dbus
  - debootstrap
  - dnsmasq-base
  - git
  - iptables
  - irqbalance
  - language-pack-en
  - liblxc1
  - lxc
  - lxc-dev
  - lxc-templates
  - python-dev
  - python-lxc
  - python3-lxc
  - systemd-container
  - pxz
nova_distro_packages:
  - genisoimage
  - git
  - iptables
  - python-openstackclient
  - libpython2.7
nova_spice_distro_packages:
  - spice-html5
nova_novnc_distro_packages:
  - libjs-jquery
  - libjs-sphinxdoc
  - libjs-underscore
  - libjs-swfobject
  - librabbitmq4
  - libyaml-0-2
nova_compute_kvm_distro_packages:
  - bridge-utils
  - genisoimage
  - kpartx
  - libvirt-bin
  - open-iscsi
  - python-guestfs
  - python3-guestfs
  - python-libvirt
  - python3-libvirt
  - qemu
  - qemu-utils
  - sysfsutils
  - vlan
  - nfs-common
  - dosfstools
  - multipath-tools
  - qemu-system
  - qemu-system-arm
  - qemu-system-mips
  - qemu-system-ppc
  - qemu-system-sparc
  - qemu-system-x86
  - qemu-system-misc
  - qemu-block-extra
  - qemu-utils
  - qemu-user
  - qemu-kvm
