---
# Preloads apt host packages for Newton OSA Release
#
# Can be run in advance of a leapfrog upgrade to Newton.
# Allows for operator to prestage apt packages on hosts
# to avoid bottleneck issues from retrieving packages
# during the maintenance.
# 
# Useful for large number of hosts in an environment to
# help reduce upgrade times.
#
# Pulls from vars for Ubuntu 14.04 LTS from
# openstack-ansible-openstack_hosts
# openstack-ansible-os_nova
# openstack-ansible-lxc_host

- name: Preflight check
  hosts: hosts
  gather_facts: false
  user: root
  tasks:
    - name: Ping check
      ping:

- name: Ensure Apt is in a healthy state across all hosts
  hosts: hosts
  gather_facts: false
  user: root
  tasks:
    - name: Ensure Apt is in a healthy state on all hosts
      shell: "dpkg -a --configure; apt install -y -f"
    - name: Refresh apt cache
      apt:
        update_cache: yes
      ignore_errors: true

- name: Preload openstack_host apt packages
  hosts: hosts
  user: root
  vars:
    openstack_host_distro_packages:
      - apparmor-utils
      - apt-transport-https
      - bridge-utils
      - build-essential
      - cgroup-lite
      - curl
      - dmeventd
      - dstat
      - ebtables
      - htop
      - iptables
      - irqbalance
      - libkmod-dev
      - libkmod2
      - lvm2
      - python-software-properties
      - python-dev
      - rsync
      - rsyslog
      - sshpass
      - sysstat
      - time
      - vlan
      - wget
  tasks:
    - name: Download apt packages but don't install
      shell: "apt-get -d -y install {{ item }}"
      with_items:
        - "{{ openstack_host_distro_packages | join(' ') }}"

- name: Preload lxc_hosts apt packages
  hosts: lxc_hosts
  user: root
  vars:
    lxc_hosts_distro_packages:
      - apparmor
      - apparmor-utils
      - bridge-utils
      - cgmanager
      - cgroup-lite
      - debootstrap
      - dnsmasq-base
      - git
      - irqbalance
      - language-pack-en
      - liblxc1
      - lxc
      - lxc-dev
      - lxc-templates
      - python-dev
      - python3-lxc
      - pxz
  tasks:
    - name: Download apt packages but don't install
      shell: "apt-get -d -y install {{ item }}"
      with_items:
        - "{{ lxc_hosts_distro_packages | join(' ') }}"

- name: Preload compute_host apt packages
  hosts: compute_hosts
  user: root
  vars:
    nova_distro_packages:
      - genisoimage
      - git
      - libpq-dev
      - iptables
    nova_spice_distro_packages:
      - spice-html5
    nova_novnc_distro_packages:
      - libjs-jquery
      - libjs-sphinxdoc
      - libjs-underscore
      - libjs-swfobject
      - librabbitmq1
      - libyaml-0-2
    nova_compute_kvm_distro_packages:
      - bridge-utils
      - genisoimage
      - kpartx
      - libvirt-bin
      - open-iscsi
      - python-libguestfs
      - python-libvirt
      - qemu
      - qemu-utils
      - sysfsutils
      - vlan
      - nfs-common
      - dosfstools
      - dosfstools-dbg
      - multipath-tools
      - qemu-system
      - qemu-system-arm
      - qemu-system-mips
      - qemu-system-ppc
      - qemu-system-sparc
      - qemu-system-x86
      - qemu-system-misc
      - qemu-block-extra
      - qemu-utils
      - qemu-user

  tasks:
    - name: Download apt packages but don't install
      shell: "apt-get -d -y install {{ item }}"
      with_items:
        - "{{ nova_distro_packages | join(' ') }}"
        - "{{ nova_compute_kvm_distro_packages | join(' ') }}"
        - "{{ nova_spice_distro_packages | join(' ') }}"
        - "{{ nova_novnc_distro_packages | join(' ') }}"
